before_script:
  - "bundle exec rubocop"
script:
  - "export CODECLIMATE_REPO_TOKEN=04853df625409de0a0f4e9126aee11bbee3428c81c20c27df6e6ab5c60bff2c8 && export JRUBY_OPTS='-X+O -J-Djruby.launch.inproc=false' && bundle exec rake neo4j:install['community-2.2.0-M01'] neo4j:start default --trace"
language: ruby
rvm:
  - 2.2.0
  - 1.9.3
  - jruby-1.7.16
  # - jruby-19mode
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b803232e5210f6134a1e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
